POST http://127.0.0.1/api/v1/user/event HTTP/1.1
Accept : application/json
Content-Type : application/json

[
    {"userId": 1, "content": "login to private room"},
    {"userId": 2, "content": "login to private room"},
    {"userId": 3, "content": "login to private room"},
    {"userId": 4, "content": "login to private room"},
    {"userId": 5, "content": "login to private room"},
    {"userId": 6, "content": "login to private room"},
    {"userId": 7, "content": "login to private room"},
    {"userId": 8, "content": "login to private room"},
    {"userId": 9, "content": "login to private room"},
    {"userId": 10, "content": "login to private room"},
    {"userId": 11, "content": "login to private room"},
    {"userId": 12, "content": "login to private room"},
    {"userId": 13, "content": "login to private room"},
    {"userId": 14, "content": "login to private room"},
    {"userId": 15, "content": "login to private room"},
    {"userId": 16, "content": "login to private room"},
    {"userId": 17, "content": "login to private room"},
    {"userId": 18, "content": "login to private room"},
    {"userId": 19, "content": "login to private room"},
    {"userId": 20, "content": "login to private room"},
    {"userId": 1, "content": "logout from private room"},
    {"userId": 2, "content": "logout from private room"},
    {"userId": 3, "content": "logout from private room"},
    {"userId": 4, "content": "logout from private room"},
    {"userId": 5, "content": "logout from private room"},
    {"userId": 6, "content": "logout from private room"},
    {"userId": 7, "content": "logout from private room"},
    {"userId": 8, "content": "logout from private room"},
    {"userId": 9, "content": "logout from private room"},
    {"userId": 10, "content": "logout from private room"},
    {"userId": 11, "content": "logout from private room"},
    {"userId": 12, "content": "logout from private room"},
    {"userId": 13, "content": "logout from private room"},
    {"userId": 14, "content": "logout from private room"},
    {"userId": 15, "content": "logout from private room"},
    {"userId": 16, "content": "logout from private room"},
    {"userId": 17, "content": "logout from private room"},
    {"userId": 18, "content": "logout from private room"},
    {"userId": 19, "content": "logout from private room"},
    {"userId": 20, "content": "logout from private room"}
]
